engines:
  duplication:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: false
  scss-lint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.scss"

exclude_paths:
  - test/
  - node_modules/
  - public/
  - coverage/
  - .idea/
  - volumes/
  - "**.yml"
  - "**.md"
  - "**.html"
  - "**.json"
  - gulpfile.js
  - LICENSE
  - src/assets/sass/defra/_spinner.scss

checks:
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 15
