ARG PARENT_VERSION=2.7.0-node22.14.0

# https://github.com/DEFRA/defra-docker-node
FROM defradigital/node:${PARENT_VERSION} AS base

USER root

WORKDIR /app

# Install app dependencies
COPY / /app
RUN npm install pm2 -g --ignore-scripts \
    && npm install --ignore-scripts

# Default service port
ARG PORT=4000

EXPOSE ${PORT}

ENTRYPOINT [ "pm2-dev", "ecosystem.config.yml" ]
