services:
  fmt:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - ./docker/env/.fmt.env
    volumes:
      - .:/app # copy everything to container, to allow pm2 to restart when a file is saved
      - /app/node_modules # ignore local node_modules
      - /app/public # ignore local public folder
    ports:
      - 4000:4000
  nginx:
    image: nginx:alpine
    environment:
      - FMT_LISTEN=3143 # we are using 3143 (same as telesales) because that is what is in the app registration
      - FMT_UPSTREAM_PORT=4000
    ports:
      - "3143:3143"
    volumes:
      - ./docker/resources/infrastructure/nginx/templates:/etc/nginx/templates
      - ./docker/resources/infrastructure/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - fmt
