version: "2.0"
services:

#######################################################
# Redis
#######################################################
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - dev_net
    mem_limit: 1024000000
    volumes:
      - ./volumes/redisdata:/data
      - ./volumes/redisconf/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    command: redis-server --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081
    mem_limit: 256000000
    depends_on:
      - redis
    restart: always
    networks:
      - dev_net

networks:
  dev_net:
    driver: bridge
