services:
  fmt:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - ./docker/env/.fmt.env
    ports:
      - 4000:4000
  nginx:
    image: nginx:alpine
    environment:
      - FMT_LISTEN=4043
      - FMT_UPSTREAM_PORT=4000
    ports:
      - "4043:4043"
    volumes:
      - ./docker/resources/infrastructure/nginx/templates:/etc/nginx/templates
      - ./docker/resources/infrastructure/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - fmt
