services:
  #######################################################
  # nginx
  #######################################################
  nginx:
    image: nginx:alpine
    environment:
      - FMT_LISTEN=4043
      - FMT_UPSTREAM_PORT=4000
      - ANGLER_LISTEN=3043
      - ANGLER_UPSTREAM_PORT=3000
    ports:
      - "4043:4043"
      - "3043:3043"
    volumes:
      - ./resources/infrastructure/nginx/templates:/etc/nginx/templates
      - ./resources/infrastructure/nginx/ssl:/etc/nginx/ssl
    deploy:
      restart_policy:
        condition: on-failure
  
  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav-db:/var/lib/clamav  # Persistent volume for ClamAV database
      - clamav-socket:/tmp/  # Mount Unix socket for communication
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  clamav-db:
  clamav-socket: