services:
  fmt:
    image: rod_catch_returns/frontend:${TAG:-latest}
    env_file:
      - ./env/.fmt.env
      - ./env/.fmt.secrets.env
    volumes:
      - ../:/app
    ports:
      - 4000:4000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  
  angler:
    image: rod_catch_returns/frontend:${TAG:-latest}
    env_file:
      - ./env/.angler.env
      - ./env/.angler.secrets.env
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
