services:
  frontend-base:
    image: rod_catch_returns/frontend-base:${TAG:-latest}
    build:
      context: ../
      dockerfile: Dockerfile.base

  frontend-fmt:
    image: rod_catch_returns/frontend-fmt:${TAG:-latest}
    build:
      context: ../
      dockerfile: Dockerfile.fmt
      additional_contexts:
        frontend-base: service:frontend-base

  frontend-angler:
    image: rod_catch_returns/frontend-angler:${TAG:-latest}
    build:
      context: ../
      dockerfile: Dockerfile.angler
      additional_contexts:
        frontend-base: service:frontend-base