name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        env:
          COOKIE_PW: 532fdfghdf62645872aaau121qsqw112
          API_PATH: /api
          API_HOSTNAME: localhost
          API_PORT: 9580
          REDIS_HOSTNAME: localhost
          REDIS_PORT: 6379
          SESSION_TTL_MS: 3600000
          API_REQUEST_TIMEOUT_MS: 20000
          CONTEXT: ANGLER
          AUTH_PW: "1234567890123456"
          CATCH_RETURNS_GOV_UK: https://www.gov.uk/catch-return
          HTTPS: false
        run: npm run test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          JAVA_HOME:
          use_embedded_jre: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
