name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:jest
  
  sonarcloud:
    name: sonarcloud
    runs-on: ubuntu-18.04
    needs: tests
    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}