name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-18.04
    
    steps:
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 5
      - name: Checkout API
        uses: actions/checkout@v2
        with:
          repository: DEFRA/rod-catch-returns-api
          path: api
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      - name: Run with Maven
        working-directory: ./api
        run: |
          ./mvnw -B compile && 
          ./mvnw -B -Dcheckstyle.skip=true -Ddependency-check.skip=true -DskipTests=true -Dspring-boot-plugin.fork.wait=5000 -Dspring-boot-plugin.fork.attempts=24 -Dspring-boot.run.arguments="--spring.profiles.active=h2" spring-boot:start && 
          curl http://localhost:9580 -I
      - name: Checkout frontend
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        env:
          COOKIE_PW: 532fdfghdf62645872aaau121qsqw112
          API_PATH: /api
          API_HOSTNAME: localhost
          API_PORT: 9580
          REDIS_HOSTNAME: localhost
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          SESSION_TTL_MS: 3600000
          API_REQUEST_TIMEOUT_MS: 20000
          CONTEXT: ANGLER
          AUTH_PW: 1234567890123456
          CATCH_RETURNS_GOV_UK: https://www.gov.uk/catch-return
          HTTPS: false
        run: curl http://localhost:9580/api/licence/B7A718 -I && npm test