name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.9'
          java-package: jdk
      - name: Start api
        run: |
          nohup java -jar api-binary/rcr_api.jar --spring.profiles.active=h2 &
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test

